(function(){function z(C,l,A){function w(n,x){if(!l[n]){if(!C[n]){var E="function"==typeof require&&require;if(!x&&E)return E(n,!0);if(q)return q(n,!0);x=Error("Cannot find module '"+n+"'");throw x.code="MODULE_NOT_FOUND",x;}x=l[n]={exports:{}};C[n][0].call(x.exports,function(D){return w(C[n][1][D]||D)},x,x.exports,z,C,l,A)}return l[n].exports}for(var q="function"==typeof require&&require,t=0;t<A.length;t++)w(A[t]);return w}return z})()({1:[function(z,C,l){var A=z("path-to-regexp").pathToRegexp;z=
function(){function w(q){var t=this;this.currentHash="/";this.routes={};this.NFoundCallbak=q;window.addEventListener("load",function(){t._refresh()},!1);window.addEventListener("hashchange",function(){t._refresh()})}w.prototype.route=function(q,t){q=A(q,[],{sensitive:!0,strict:!0});this.routes[q]=t};w.prototype._refresh=function(){this.currentHash=location.hash.slice(1)||"/";for(var q=0,t=Object.keys(this.routes);q<t.length;q++){var n=t[q];if(eval(n).test(this.currentHash)){this.routes[n](this.currentHash);
return}}this.NFoundCallbak&&this.NFoundCallbak(this.currentHash)};return w}();window.VueRouter=z},{"path-to-regexp":2}],2:[function(z,C,l){function A(a){for(var e=[],b=0;b<a.length;){var d=a[b];if("*"===d||"+"===d||"?"===d)e.push({type:"MODIFIER",index:b,value:a[b++]});else if("\\"===d)e.push({type:"ESCAPED_CHAR",index:b++,value:a[b++]});else if("{"===d)e.push({type:"OPEN",index:b,value:a[b++]});else if("}"===d)e.push({type:"CLOSE",index:b,value:a[b++]});else if(":"===d){var g="";for(d=b+1;d<a.length;){var f=
a.charCodeAt(d);if(48<=f&&57>=f||65<=f&&90>=f||97<=f&&122>=f||95===f)g+=a[d++];else break}if(!g)throw new TypeError("Missing parameter name at "+b);e.push({type:"NAME",index:b,value:g});b=d}else if("("===d){g=1;f="";d=b+1;if("?"===a[d])throw new TypeError('Pattern cannot start with "?" at '+d);for(;d<a.length;)if("\\"===a[d])f+=a[d++]+a[d++];else{if(")"===a[d]){if(g--,0===g){d++;break}}else if("("===a[d]&&(g++,"?"!==a[d+1]))throw new TypeError("Capturing groups are not allowed at "+d);f+=a[d++]}if(g)throw new TypeError("Unbalanced pattern at "+
b);if(!f)throw new TypeError("Missing pattern at "+b);e.push({type:"PATTERN",index:b,value:f});b=d}else e.push({type:"CHAR",index:b,value:a[b++]})}e.push({type:"END",index:b,value:""});return e}function w(a,e){void 0===e&&(e={});var b=A(a);a=e.prefixes;a=void 0===a?"./":a;e="[^"+n(e.delimiter||"/#?")+"]+?";for(var d=[],g=0,f=0,r="",h=function(B){if(f<b.length&&b[f].type===B)return b[f++].value},u=function(B){var y=h(B);if(void 0!==y)return y;y=b[f];throw new TypeError("Unexpected "+y.type+" at "+
y.index+", expected "+B);},p=function(){for(var B="",y;y=h("CHAR")||h("ESCAPED_CHAR");)B+=y;return B};f<b.length;){var c=h("CHAR"),k=h("NAME"),m=h("PATTERN");if(k||m)c=c||"",-1===a.indexOf(c)&&(r+=c,c=""),r&&(d.push(r),r=""),d.push({name:k||g++,prefix:c,suffix:"",pattern:m||e,modifier:h("MODIFIER")||""});else if(c=c||h("ESCAPED_CHAR"))r+=c;else if(r&&(d.push(r),r=""),h("OPEN")){c=p();k=h("NAME")||"";m=h("PATTERN")||"";var v=p();u("CLOSE");d.push({name:k||(m?g++:""),pattern:k&&!m?e:m,prefix:c,suffix:v,
modifier:h("MODIFIER")||""})}else u("END")}return d}function q(a,e){void 0===e&&(e={});var b=e&&e.sensitive?"":"i",d=e.encode,g=void 0===d?function(h){return h}:d;e=e.validate;var f=void 0===e?!0:e,r=a.map(function(h){if("object"===typeof h)return new RegExp("^(?:"+h.pattern+")$",b)});return function(h){for(var u="",p=0;p<a.length;p++){var c=a[p];if("string"===typeof c)u+=c;else{var k=h?h[c.name]:void 0,m="?"===c.modifier||"*"===c.modifier,v="*"===c.modifier||"+"===c.modifier;if(Array.isArray(k)){if(!v)throw new TypeError('Expected "'+
c.name+'" to not repeat, but got an array');if(0===k.length){if(m)continue;throw new TypeError('Expected "'+c.name+'" to not be empty');}for(m=0;m<k.length;m++){v=g(k[m],c);if(f&&!r[p].test(v))throw new TypeError('Expected all "'+c.name+'" to match "'+c.pattern+'", but got "'+v+'"');u+=c.prefix+v+c.suffix}}else if("string"===typeof k||"number"===typeof k){v=g(String(k),c);if(f&&!r[p].test(v))throw new TypeError('Expected "'+c.name+'" to match "'+c.pattern+'", but got "'+v+'"');u+=c.prefix+v+c.suffix}else if(!m)throw new TypeError('Expected "'+
c.name+'" to be '+(v?"an array":"a string"));}}return u}}function t(a,e,b){void 0===b&&(b={});b=b.decode;var d=void 0===b?function(g){return g}:b;return function(g){var f=a.exec(g);if(!f)return!1;g=f[0];for(var r=f.index,h=Object.create(null),u=function(c){if(void 0===f[c])return"continue";var k=e[c-1];h[k.name]="*"===k.modifier||"+"===k.modifier?f[c].split(k.prefix+k.suffix).map(function(m){return d(m,k)}):d(f[c],k)},p=1;p<f.length;p++)u(p);return{path:g,index:r,params:h}}}function n(a){return a.replace(/([.+*?=^!:${}()[\]|/\\])/g,
"\\$1")}function x(a,e,b){a=a.map(function(d){return D(d,e,b).source});return new RegExp("(?:"+a.join("|")+")",b&&b.sensitive?"":"i")}function E(a,e,b){void 0===b&&(b={});var d=b.strict;d=void 0===d?!1:d;var g=b.start,f=void 0===g?!0:g;g=b.end;var r=void 0===g?!0:g;g=b.encode;var h=void 0===g?function(v){return v}:g;g="["+n(b.endsWith||"")+"]|$";var u="["+n(b.delimiter||"/#?")+"]";f=f?"^":"";for(var p=0;p<a.length;p++){var c=a[p];if("string"===typeof c)f+=n(h(c));else{var k=n(h(c.prefix)),m=n(h(c.suffix));
c.pattern?(e&&e.push(c),f=k||m?"+"===c.modifier||"*"===c.modifier?f+("(?:"+k+"((?:"+c.pattern+")(?:"+m+k+"(?:"+c.pattern+"))*)"+m+")"+("*"===c.modifier?"?":"")):f+("(?:"+k+"("+c.pattern+")"+m+")"+c.modifier):f+("("+c.pattern+")"+c.modifier)):f+="(?:"+k+m+")"+c.modifier}}r?(d||(f+=u+"?"),f+=b.endsWith?"(?="+g+")":"$"):(a=a[a.length-1],a="string"===typeof a?-1<u.indexOf(a[a.length-1]):void 0===a,d||(f+="(?:"+u+"(?="+g+"))?"),a||(f+="(?="+u+"|"+g+")"));return new RegExp(f,b&&b.sensitive?"":"i")}function D(a,
e,b){if(a instanceof RegExp){if(e){b=/\((?:\?<(.*?)>)?(?!\?)/g;for(var d=0,g=b.exec(a.source);g;)e.push({name:g[1]||d++,prefix:"",suffix:"",modifier:"",pattern:""}),g=b.exec(a.source)}return a}return Array.isArray(a)?x(a,e,b):E(w(a,b),e,b)}Object.defineProperty(l,"__esModule",{value:!0});l.pathToRegexp=l.tokensToRegexp=l.regexpToFunction=l.match=l.tokensToFunction=l.compile=l.parse=void 0;l.parse=w;l.compile=function(a,e){return q(w(a,e),e)};l.tokensToFunction=q;l.match=function(a,e){var b=[];a=D(a,
b,e);return t(a,b,e)};l.regexpToFunction=t;l.tokensToRegexp=E;l.pathToRegexp=D},{}]},{},[1]);